<a href="https://colab.research.google.com/github/Julianmoralez/Retos-Colab/blob/Retos-Colab/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Caso de estudio **
En este documento se desaroolla y analiza un modelo naive Bayes para la preaprobacion de creditos dn una entidad fincanciera utilizando las variables socioeconomicas de un solicitante de credito

De acuerdo con lo anterior, las variables socioeconomicas son:
**Edad**: Es la edad que posee el solicitante al momento de solicitar un credito.

**Ingresos**: ingresos recibidos por una persona como resultado de una actividad comercial

**Egresos**: son los gastos mensuales del Solicitante. Gastos de personas a cargo, hijos y servicios publicos.

**Monto (EDAD)**: Indica el dinero que una persona solicita a una entidad financiera como credito.






0. Se procede con la carga de las librerias de trabajo

In [ ]:
# ================================
# LIBRERÍAS BÁSICAS
# ================================

from ast import Import
# Módulo interno de Python para trabajar con el Árbol de Sintaxis Abstracta (AST).
# Sirve para analizar o manipular código Python como texto.
# En este caso NO es necesario para machine learning ni análisis de datos.
#  Se puede eliminar sin afectar el modelo.

import numpy as np
# NumPy: librería numérica por excelencia.
# Se usa para:
# - Operaciones matemáticas y estadísticas
# - Manejo de arreglos y matrices
# - Cálculos rápidos y eficientes
# Es la base de muchas otras librerías (como pandas y sklearn).

import pandas as pd
# Pandas: manejo y análisis de datos en forma de tablas (DataFrames).
# Se usa para:
# - Cargar datos (CSV, Excel, etc.)
# - Limpiar y transformar datos
# - Seleccionar columnas y filas
# Muy usada en la fase de preparación de datos.

import matplotlib.pyplot as plt
# Matplotlib: librería básica para visualización de datos.
# Se usa para:
# - Gráficos de líneas, barras, dispersión, histogramas
# - Visualizar resultados y patrones en los datos
# Es la base sobre la que trabaja seaborn.

import seaborn as sns
# Seaborn: librería de visualización basada en matplotlib.
# Se usa para:
# - Gráficos más estéticos y estadísticos
# - Mapas de calor, boxplots, gráficos de correlación
# Ideal para análisis exploratorio de datos (EDA).

# ================================
# LIBRERÍAS DE MACHINE LEARNING
# ================================

from sklearn.naive_bayes import GaussianNB
# Modelo de Naive Bayes Gaussiano.
# Se usa para:
# - Clasificación supervisada
# - Datos numéricos con distribución normal
# Es un modelo simple, rápido y muy usado en clasificación inicial.

from sklearn.model_selection import train_test_split
# Función para dividir los datos en:
# - Conjunto de entrenamiento (train)
# - Conjunto de prueba (test)
# Permite evaluar el modelo con datos que no ha visto antes.

from sklearn.metrics import accuracy_score
# Métrica de evaluación del modelo.
# Calcula el porcentaje de predicciones correctas.
# Es útil cuando las clases están balanceadas.

from sklearn.metrics import confusion_matrix
# Matriz de confusión.
# Permite ver:
# - Verdaderos positivos
# - Verdaderos negativos
# - Falsos positivos
# - Falsos negativos
# Ayuda a entender en qué se equivoca el modelo.

from sklearn.metrics import classification_report
# Reporte completo de clasificación.
# Muestra:
# - Precisión (precision)
# - Exhaustividad (recall)
# - F1-score
# - Soporte (support)
# Es ideal para evaluar modelos de clasificación de forma detallada.




1. Se cargan los datos de trabajo de la base de datos BaseAAA

In [ ]:

from os import read
nxl='/content/drive/MyDrive/Analitica de negocios/1. SolicitantesCrédito(USD).xlsx'
XDB=pd.read_excel(nxl,sheet_name=1) #leer el documento cargado con la variable NXL
XDB.head(100) #Es para mostrar el encabezado de esta variable

#Selecionamos variables de trabajo
XD=XDB[['Edad', 'Ingresos', 'Egresos','Monto (EAD)']] #Variables de trabajo
XD.head(11)

yd=XDB[['PreApr']] #esta la variable de decision
yd.head()




,PreApr
0,1
1,1
2,0
3,1
4,1


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


2. Implementar modelo

In [ ]:
mnb=GaussianNB ()
mnb.fit(XD,yd) #Ajustar Variables entrada - Salida
#Mostramos las medias de las variables
u=mnb.theta_
sigma=mnb.var_;sigma=np.sqrt(sigma)
print("'Edad', 'Ingresos', 'Egresos','Monto (EAD)'")
print(u)
print("Las desviaciones son:")
print(sigma)

'Edad', 'Ingresos', 'Egresos','Monto (EAD)'
[[  40.98411626  431.42680644  401.54995644  289.41445941]
 [  41.10752688 1029.98947251  900.19312144  781.2021157 ]]
Las desviaciones son:
[[ 12.21303268 325.79791497 342.77286087 235.95783541]
 [ 12.25106493 472.43342807 525.43337837 469.90038088]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Analisis de resultados**
De los resultados arrojados por el modelo, podemo observar que la categoria de preAprobados posee ingresos superiores a las categorias de preNegados, esto indica claramente la predominancia de las variable para aprobar creditos, es importante mencionar que la edad es mayor para los PreAprobados que los PreNegados, lo que indica que el banco busca personas con mayor experiencia crediticia, Podemos decir igualmente, que los PreAprobados tienen egresos superiores a los de la categoria Prenegados, Sin embargo, los preAprobados solicitantes con montos superiores a los de la categoria de prenegados, esto es un indicador de la capacidad de este grupo para hacer frente a un credito


3. se procede con la evaluacion del modelo. para la evaluacion de este tipo de modelo se tuiliza la matriz de confusión

In [ ]:
ydp=mnb.predict(XD) #Esto es lo que el modelo aprende - ydp de pronostico
cm=confusion_matrix(yd,ydp)
print(cm)

# Se determinan las metricas de la matriz de confusion
VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1]; TDatos=len(XDB)

#1. Exactitud: funcionamiento general del modelo
Exactitud=(VP+VN)/TDatos
print("Exactitud:",Exactitud) #Si pasa MAS DEL 75% SIGNIFICA QUE ES UN BUEN MODELO

#2. Tasa Error: porcentaje de fallos del sistema
TasaError=(FP+FN)/TDatos
print("Tasa Error:",TasaError)

#3, Sensibilidad, como se comporto con respecto a los positivos solamente
Sensibilidad=VP/(VP+FN)
print("Sensibilidad:",Sensibilidad)

#4, especificidad, COmo se comporta pronosticando negativos
especificidad=VN/(VN+FP)
print("especificidad", especificidad)

# 5, Precision, Es una version de Como se comporta el modelo frente a los
# positivos solamente
Precision=VP/(VP+FP)
print("Precision:",Precision)

# 6, Prediccion Negativa, Como funciona el modelo pronosticando creditos prenegados
PrediccionNegativa=VN/(VN+FN)
print("PrediccionNegativa:",PrediccionNegativa)


[[2502  457]
 [ 937 1946]]
Exactitud: 0.7613830879835672
Tasa Error: 0.23861691201643273
Sensibilidad: 0.6749913284772806
especificidad 0.8455559310577898
Precision: 0.8098210570120683
PrediccionNegativa: 0.7275370747310265


**Analsis de resultados**
De acuerdo con los resultados segun los datos podemos observar que el modelo alcanzo una Exactitud por encima del 75% en promedio, lo que indica un buen comportamiento del modelo frente a la clasificacion de los solicitantes de credito frente a la PreApr y la PreNegacion. Se descata la precision con un 80.9% lo que indica el buen funcionamiento del modelo frente a la preaprobacion de creditos, Es importante tener en cuenta que se puede observar el buen comportamiento del modelo frente a la preNegacion de creditos, tal y como lo demuestra el indice de especificidad del modelo, el cual estuvo por encima del 84% en promedio.

Es importante mencionar que la **Exactitud** queda por debajo del 80% ya que esta metrica se ve afectada por los errores en clasificacion de solicitantes de credito

Lo que se evidencia a traves de la **sensibilidad y Prediccion Negativa**


4. Evaluamos un solicitante

In [ ]:
XP=[34,1500,800,1000]
ydc=mnb.predict([XP])
print(ydc)
if ydc[0] == 1:
    print("Aprobado")
else:
    print("No Aprobado")

[1]
Aprobado


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
